name: SimpleLuckPermsFormatter
main: de.nycode.slpf.SimpleLuckPermsFormatter
version: 1.0.2
api-version: 1.13
authors:
  - NyCode
website: https://github.com/NyCodeGHG/SimpleLuckPermsFormatter
depend:
  - LuckPerms
